### ISSUE TITLE
TypeError: invalid_argument

### ISSUE THREAD

**Issue by jkawamoto** [herumi/mcl-wasm#1]
`TypeError: invalid_argument` sometime occurs while initializing this library.

Since this error came from `_wrapInput`, I added the logging function: 

```js
console.debug(`buf = ${buf}, buf.length = ${buf.length}`)
```

after [L119 of `mcl.js`](https://github.com/herumi/mcl-wasm/blob/master/mcl.js#L119) and got the output:

```js
console.debug ../../node_modules/mcl-wasm/mcl.js:120
buf = 8762084894755259, buf.length = undefined

console.debug ../../node_modules/mcl-wasm/mcl.js:120
buf = 215,238,14,19,59,68,221,151,138,149,14,154,104,149,241,57,75,99,68,244,112,22,61,137,86,127,251,44,228,93,38,170, buf.length = 32

TypeError: invalid_argument
at Int8Array.set (native)
at ../../node_modules/mcl-wasm/mcl.js:129:21
at exports.G1._setter (../../node_modules/mcl-wasm/mcl.js:227:19)
at exports.G1.setHashOf (../../node_modules/mcl-wasm/mcl.js:360:14)
at Object.exports.hashAndMapToG1.s [as hashAndMapToG1] (../../node_modules/mcl-wasm/mcl.js:588:9)
```

It seems `buf` is expected to be an array but sometimes it has a number, and hence `Int8Array.set` is crashed.

**Comment by jkawamoto** [comment]
Ah, that's true. The error occurred while calling hashAndMapToG1.

I did some unusual things to use this library from [jest](https://facebook.github.io/jest/). Here is the essence of the code:

```js
const mcl = require('../mcl')
const fs = require('fs')

describe('mcl-wasm module', () => {

  beforeAll(() => {
    global.fetch = async req => {
      const buf = fs.readFileSync(req)
      return {
        ok: true,
        arrayBuffer: async () => Uint8Array.from(buf).buffer,
      }
    }
  })

  test('initialize and hashAndMapToG1', async () => {
    await mcl.init()
    mcl.hashAndMapToG1(1)
  })

})
```

And, I got the output:

```js
TypeError: invalid_argument
    at Int8Array.set (native)
    at /Users/junpei/src/github.com/jkawamoto/mcl-wasm/mcl.js:128:21
    at exports.G1._setter (/Users/junpei/src/github.com/jkawamoto/mcl-wasm/mcl.js:216:19)
    at exports.G1.setHashOf (/Users/junpei/src/github.com/jkawamoto/mcl-wasm/mcl.js:326:14)
    at Object.exports.hashAndMapToG1.s [as hashAndMapToG1] (/Users/junpei/src/github.com/jkawamoto/mcl-wasm/mcl.js:538:9)
    at Object.test (/Users/junpei/src/github.com/jkawamoto/mcl-wasm/__test__/test.js:18:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by herumi** [comment]
>mcl.hashAndMapToG1(1)

hashAndMapToG1() accepts only string or Uint8Array.
Please use `hashAndMapToG1("1")` or `hashAndMapToG1(new Uint8Array([1])`.
# These values are not same. 
I will write document of mcl later.

**Comment by jkawamoto** [comment]
Thanks! Converting the number to a string works for me.

I'll close this issue.

**Comment by herumi** [comment]
I've fixed mcl.js to check type(https://github.com/herumi/mcl-wasm/commit/9c61b5a50bb453a26f2eda3ac3857c1f8f92a12c)
